// Even Fibonacci numbers by Ryan Adi Saputra

/*
    Question:
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


#include <iostream>
using namespace std;

int main() {
    int total = 0;
 
	int a = 1;
	int b = 2;
	int sum = 0;
 
	while (b <= 4000000) {
		sum = a + b;
		if (b % 2 == 0) {
			total += b;
		}
		a = b;
		b = sum;
	}
 
	cout << total;
    return 0;
}




// Expected Answer: 4613732